package com.shop.ecommerce.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;       // for date and time
import java.util.List;
import java.util.ArrayList;

@Entity
@Table(name = "users")
public class User {

    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @Setter
    @Getter
    @Column(name = "user_name", nullable = false, unique = true)
    private String userName;
    
    @Setter
    @Getter
    @Column(nullable = false, unique = true)
    private String email;
    
    @Setter
    @Getter
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;
    
    @Setter
    @Getter
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Setter
    @Getter
    @Column(name = "is_guest")
    private boolean isGuest;

    // table for user search history to know how many times a user searched for keyword (example : "laptop : 4 times")
    @Setter
    @Getter
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<UserSearchHistory> searchHistory;

    @Setter
    @Getter
    @ElementCollection
    @CollectionTable(name = "user_purchase_history", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "product_id")
    private List<Integer> purchaseHistory;
    
    @Setter
    @Getter
    @ElementCollection
    @CollectionTable(name = "user_wishlist", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "product_id")
    private List<Integer> wishList;
    
    @Setter
    @Getter
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<CartItem> cartItems;

    // Default constructor required by JPA
    public User() {
        this.searchHistory = new ArrayList<UserSearchHistory>();
        this.purchaseHistory = new ArrayList<Integer>();
        this.wishList = new ArrayList<Integer>();
        this.cartItems = new ArrayList<CartItem>();
    }


    // removed id in constructor (generated by database)
    // User Constructor
    public User(String userName, String email, String passwordHash, LocalDateTime createdAt) {
        this.userName = userName;
        this.email = email;
        this.passwordHash = passwordHash;
        this.createdAt = LocalDateTime.now();
        this.isGuest = true;
        this.searchHistory = new ArrayList<UserSearchHistory>();
        this.purchaseHistory = new ArrayList<Integer>();
        this.wishList = new ArrayList<Integer>();
        this.cartItems = new ArrayList<CartItem>();
    }

}